aead-encrypted-array = [ +aead-encrypted ]
aead-encrypted = [
  bstr,              ; nonce of N_MIN to N_MAX (inclusive)
  bstr,              ; the encryption ciphertext output of a
                     ;   bstr-encoded-salted
  bstr               ; the corresponding authentication tag
]

