sd-cwt-types = sd-cwt-issued / kbt-cwt

sd-cwt-issued = #6.18([
   protected: bstr .cbor sd-protected,
   sd-unprotected,
   payload: bstr .cbor sd-payload,
   signature: bstr
])

kbt-cwt = #6.18([
   protected: bstr .cbor kbt-protected,
   kbt-unprotected,
   payload: bstr .cbor kbt-payload,
   signature: bstr
])

sd-protected = {
   &(typ: 16) ^ => "application/sd-cwt" / TBD11,
   &(alg: 1) ^ => int,
   ? &(kid: 4) ^ => bstr,
   ? &(CWT_Claims: 15) ^ => issued_sd_cwt_map,
   ? &(sd_alg: TBD2) ^ => int,        ; -16 for sha-256
   ? &(sd_aead: TBD7) ^ => uint .size 2,
   * label => safe_value
}

kbt-protected = {
   &(typ: 16) ^ => "application/kb+cwt" / TBD12,
   &(alg: 1) ^ => int,
   &(kcwt: 13) ^ => sd-cwt-issued,
   * label => safe_value
}

sd-unprotected = {
   ? &(sd_claims: TBD1) ^ => salted-array,
   ? &(sd_aead_encrypted_claims: TBD6) ^ => aead-encrypted-array,
   * label => safe_value
}

kbt-unprotected = {
   * label => safe_value
}

sd-payload = {
    ; standard claims
      &(iss: 1) ^ => tstr, ; "https://issuer.example"
    ? &(sub: 2) ^ => tstr, ; "https://device.example"
    ? &(aud: 3) ^ => tstr, ; "https://verifier.example/app"
    ? &(exp: 4) ^ => num,  ; 1883000000
    ? &(nbf: 5) ^ => num,  ; 1683000000
    ? &(iat: 6) ^ => num,  ; 1683000000
    ? &(cti: 7) ^ => bstr,
      &(cnf: 8) ^ => safe_map, ; key confirmation
    ? &(cnonce: 39) ^ => bstr,
    ;
    ? &(redacted_claim_keys: REDACTED_KEYS) ^ => [ * bstr ],
    * issued_sd_cwt_label => issued_sd_cwt_value
}

kbt-payload = {
      &(aud: 3) ^ => tstr, ; "https://verifier.example/app"
    ? &(exp: 4) ^ => num,  ; 1883000000
    ? &(nbf: 5) ^ => num,  ; 1683000000
      &(iat: 6) ^ => num,  ; 1683000000
    ? &(cnonce: 39) ^ => bstr,
    * label => safe_value
}

; CWT legal values only
safe_map = { * label => safe_value }

safe_value =
  int / tstr / bstr /
  [ * safe_value ] /
  safe_map /
  #6.<safe_tag>(safe_value) / #7.<safe_simple> / float

; legal values in issued SD-CWT
issued_sd_cwt_map = { * issued_sd_cwt_label => issued_sd_cwt_value }

issued_sd_cwt_label = label / REDACTED_KEYS

issued_sd_cwt_value =
  int / tstr / bstr /
  [ * issued_sd_cwt_value ] /
  issued_sd_cwt_map /
  #6.<safe_tag>(issued_sd_cwt_value) / #7.<safe_simple> / float


; legal values in claim set sent to Issuer
preissuance_label = label /
                    #6.<TO_BE_REDACTED>(label) /
                    #6.<TO_BE_DECOY>(int .gt 0)


preissuance_map = { * preissuance_label => preissuance_value }

preissuance_value =
  int / tstr / bstr /
  [ * preissuance_value ] /
  preissuance_map /
  #6.<safe_tag>(preissuance_value) / #7.<safe_simple> / float


label = int / tstr .size (1..255)
safe_tag = 1..57 / 59..60 / 62..MAX_u64  ; exclude to be redacted
                                         ;     and to be decoy
safe_simple =  0..23 / 32..58 / 60..255  ; exclude redacted keys array
MAX_u64 = 18446744073709551615           ; 2^64 - 1


salted-array = [ *bstr-encoded-salted ]
bstr-encoded-salted = bstr .cbor salted-entry
salted-entry = salted-claim / salted-element / decoy
salted-claim = [
  bstr .size 16,     ; 128-bit salt
  any,               ; claim value
  (int / text)       ; claim name
]
salted-element = [
  bstr .size 16,     ; 128-bit salt
  any                ; claim value
]
decoy = [
  bstr .size 16      ; 128-bit salt
]

aead-encrypted-array = [ *aead-encrypted ]
aead-encrypted = [
  bstr .size 16,     ; 128-bit nonce
  bstr,              ; the encryption ciphertext output of a
                     ;   bstr-encoded-salted
  bstr               ; the corresponding authentication tag
]

num = int / float
TBD1 = 17
TBD2 = 18
TBD6 = 19
TBD7 = 20

;TBD3 = 58;  CBOR tag wrapping to-be-redacted keys or elements

TBD11 = 66
TBD12 = 67

TO_BE_REDACTED = 58  ; CBOR tag wrapping to-be-redacted keys or elements
TO_BE_DECOY = 61     ; CBOR tag indicating a decoy value to be inserted

; REDACTED_KEYS is to be used in CDDL payloads that are meant to
; convey that a map key is redacted.
REDACTED_KEYS = #7.59  ; #7.<TBD4>
;TBD4 = 59          ; for CBOR simple value 59

; redacted_claim_element is to be used in CDDL payloads that contain
; array elements that are meant to be redacted.
;redacted_claim_element = #6.60( bstr .size 16 )  ; #6.<TBD5>(bstr)
;TBD5 = 60; CBOR tag wrapping redacted_claim_element
